root: ./

structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
  enterprise/installation: 0_7_enterprise/installation/README.md
  enterprise/installation/: 0_7_enterprise/installation/README.md
  enterprise-edition/installation: 0_7_enterprise/installation/README.md
  enterprise-edition/installation/: 0_7_enterprise/installation/README.md
  enterprise/post-installation: 0_7_enterprise/post-installation/README.md
  enterprise/post-installation/: 0_7_enterprise/post-installation/README.md
  enterprise/advanced-tuning/index-1: 0_7_enterprise/s3/README.md
  cluster/overview: 02_getting-started/connect-your-computer/README.md
  cluster/overview/: 02_getting-started/connect-your-computer/README.md
  ann_format: 03_03_/Annotation-JSON-format/00_ann_format_navi.md
  ann_format/: 03_/Annotation-JSON-format/00_ann_format_navi.md
  /import-export/supervisely-format: 03_data-organization/Annotation-JSON-format/00_ann_format_navi.md
  /import-export/supervisely-format/: 03_/Annotation-JSON-format/00_ann_format_navi.md
  customization/agents/status: /connect-your-computer/agents/status_and_troubleshooting/status.md
  customization/agents/status/: /connect-your-computer/agents/status_and_troubleshooting/status.md
  customization/agents: /connect-your-computer/README.md
  customization/agents/: /connect-your-computer/README.md
